

export const KEGIATAN = {
    WEDDING: "WEDDING",
   
};
export const CODE_FITUR = {
    SHOW_BRIDE_NAME: "SHOW_BRIDE_NAME",
    SHOW_GALERI:"SHOW_GALERI",
    ABSENT_ATTANDANCE: "ABSENT_ATTANDANCE",

};

export const CODE_TEMPLATE = {
    TEMPLATE1: "TMPT1",
    TEMPLATE2:"TMPT2",
    TEMPLATE3: "TMPT3",

};