

export const KEGIATAN = {
    WEDDING: "WEDDING",
   
};
export const CODE_FITUR = {
    SHOW_BRIDE_NAME: "SHOW_BRIDE_NAME",
    SHOW_PARENT_NAME:"SHOW_PARENT_NAME",
    SHOW_EVENT_LOCATION:"SHOW_EVENT_LOCATION",
    SHOW_EVENT_DATE:"SHOW_EVENT_DATE",
    SHOW_MAP_LOCATION:"SHOW_MAP_LOCATION",
    SHOW_COUNTDOWN:"SHOW_COUNTDOWN",
    SHOW_GALLERY:"SHOW_GALLERY",
    SHOW_LOVE_STORY:"SHOW_LOVE_STORY",
    SHOW_EVENT_SCHEDULE:"SHOW_EVENT_SCHEDULE",
    SHOW_DRESS_CODE:"SHOW_DRESS_CODE",
    SHOW_MUSIC:"SHOW_MUSIC",
    SHOW_LIVE_STREAMING:"SHOW_LIVE_STREAMING",
    SHOW_RSVP:"SHOW_RSVP",
    SHOW_ATTENDANCE:"SHOW_ATTENDANCE",
    SHOW_GUEST_BOOK:"SHOW_GUEST_BOOK",
    SHOW_WEDDING_GIFT:"SHOW_WEDDING_GIFT",
    SHOW_QR_CHECKIN:"SHOW_QR_CHECKIN",
    SHOW_SEAT_NUMBER:"SHOW_SEAT_NUMBER",
    SHOW_INVITATION_TO:"SHOW_INVITATION_TO",
    SHOW_SHARE_BUTTON:"SHOW_SHARE_BUTTON",
    SHOW_HEALTH_PROTOCOL:"SHOW_HEALTH_PROTOCOL",
    SHOW_CONTACT_PERSON:"SHOW_CONTACT_PERSON",
    SHOW_THANK_YOU_NOTE:"SHOW_THANK_YOU_NOTE",
    SHOW_VIDEO: "SHOW_VIDEO",
};

export const CODE_TEMPLATE = {
    TEMPLATE1: "TMPT1",
    TEMPLATE2:"TMPT2",
    TEMPLATE3: "TMPT3",

};